es = [
    "Reanudación del período de sesiones Declaro reanudado el período de sesiones del Parlamento Europeo, interrumpido el viernes 17 de diciembre pasado, y reitero a Sus Señorías mi deseo de que hayan tenido unas buenas vacaciones.",
    "Como todos han podido comprobar, el gran 'efecto del año 2000' no se ha producido.En cambio, los ciudadanos de varios de nuestros países han sido víctimas de catástrofes naturales verdaderamente terribles.",
    "Sus Señorías han solicitado un debate sobre el tema para los próximos días, en el curso de este período de sesiones.",
    "A la espera de que se produzca, de acuerdo con muchos colegas que me lo han pedido, pido que hagamos un minuto de silencio en memoria de todas las víctimas de las tormentas, en los distintos países de la Unión Europea afectados.",
    "Invito a todos a que nos pongamos de pie para guardar un minuto de silencio.",
    "(El Parlamento, de pie, guarda un minuto de silencio)",
    "Señora Presidenta, una cuestión de procedimiento.",
    "Sabrá usted por la prensa y la televisión que se han producido una serie de explosiones y asesinatos en Sri Lanka.",
    "Una de las personas que recientemente han asesinado en Sri Lanka ha sido al Sr. Kumar Ponnambalam, quien hace pocos meses visitó el Parlamento Europeo.",
    "¿Sería apropiado que usted, Señora Presidenta, escribiese una carta al Presidente de Sri Lanka expresando las condolencias del Parlamento por esa y otras muertes violentas, pidiéndole que haga todo lo posible para encontrar una reconciliación pacífica ante la extremadamente difícil situación que está viviendo su país?",
    "Sí, señor Evans, pienso que una iniciativa como la que usted acaba de sugerir sería muy adecuada.",
    "Si la Asamblea está de acuerdo, haré lo que el señor Evans acaba de sugerir.",
    "Señora Presidenta, una cuestión de procedimiento.",
    "Me gustaría que me asesorara sobre el Artículo 143 concerniente a la inadmisibilidad.",
    "Mi pregunta se refiere a un asunto del que se hablará el jueves, día que en volveré a plantearla.",
    "El informe Cunha sobre los programas de dirección plurianual se presenta al Parlamento el jueves y contiene una propuesta en el apartado 6 en torno a una forma de penalizaciones basada en cuotas que debe aplicarse a los países que no cumplan anualmente sus objetivos de reducción de flota.",
    "El informe estipula que se debe aplicarse a pesar del principio de estabilidad relativa.",
    "Creo que el principio de estabilidad relativa es un principio legal fundamental de las políticas pesqueras comunitarias, por lo que una propuesta que lo subvierta es legalmente inadmisible.",
    "Quiero saber si se puede hacer este tipo de objeción a lo que sólo es un informe, no una propuesta legislativa, y si es algo que puedo plantear el jueves.",
    "Su Señoría, si así lo desea, podrá plantear esta cuestión en ese momento, es decir, el jueves antes de que se presente el informe.",
    "Señora Presidenta, coincidiendo con el primer período parcial de sesiones de este año del Parlamento Europeo, lamentablemente, en los Estados Unidos, en Texas, se ha fijado para el próximo jueves la ejecución de un condenado a la pena capital, un joven de 34 años que llamaremos con el nombre de Hicks.",
    "A petición de un diputado francés, el Sr. Zimeray, se ha presentado una solicitud, cuyos firmantes han sido numerosos y entre los cuales me cuento, sin embargo, de conformidad con la posición constantemente expresada por el Parlamento Europeo y por toda la Comunidad europea, le pido que intervenga con el prestigio de su cargo y de la Institución que representa ante el Presidente y el Gobernador del Estado de Texas, Sr. Bush, que tiene la facultad de suspender la condena a muerte y de indultar al condenado.",
    "Todo ello, de conformidad con los principios que siempre hemos apoyado.",
    "Gracias, señor Segni, lo haré de muy buen grado.",
    "Está, sin duda, dentro de la línea de las posiciones que nuestro Parlamento siempre ha adoptado.",
    "Señora Presidenta, quisiera llamar la atención de usted acerca de un caso del que se ha ocupado una y otra vez este Parlamento.",
    "Es el caso de Alexander Nikitin.",
    "Todos celebramos aquí que el tribunal le haya declarado inocente y que haya puesto de manifiesto que también en Rusia el acceso a la información sobre el medio ambiente es un derecho constitucional.",
    "Sin embargo, sucede que va a ser acusado de nuevo, pues el fiscal interpondrá un recurso.",
    "Sabemos y lo hemos afirmado realmente en muchas resoluciones -precisamente en la última sesión plenaria del año pasado- que éste no es solamente un caso jurídico y que es un error acusar a Alexander Nikitin de conducta criminal y de traición, porque nosotros, como afectados por sus resultados, obtengamos provecho de ella."
]

en =[
    "Resumption of the session I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period.",
    "Although, as you will have seen, the dreaded 'millennium bug' failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful.",
    "You have requested a debate on this subject in the course of the next few days, during this part-session.",
    "In the meantime, I should like to observe a minute' s silence, as a number of Members have requested, on behalf of all the victims concerned, particularly those of the terrible storms, in the various countries of the European Union.",
    "Please rise, then, for this minute' s silence.",
    "(The House rose and observed a minute' s silence)",
    "Madam President, on a point of order.",
    "You will be aware from the press and television that there have been a number of bomb explosions and killings in Sri Lanka.",
    "One of the people assassinated very recently in Sri Lanka was Mr. Kumar Ponnambalam, who had visited the European Parliament just a few months ago.",
    "Would it be appropriate for you, Madam President, to write a letter to the Sri Lankan President expressing Parliament's regret at his and the other violent deaths in Sri Lanka and urging her to do everything she possibly can to seek a peaceful reconciliation to a very difficult situation?",
    "Yes, Mr Evans, I feel an initiative of the type you have just suggested would be entirely appropriate.",
    "If the House agrees, I shall do as Mr Evans has suggested.",
    "Madam President, on a point of order.",
    "I would like your advice about Rule 143 concerning inadmissibility.",
    "My question relates to something that will come up on Thursday and which I will then raise again.",
    "The Cunha report on multiannual guidance programmes comes before Parliament on Thursday and contains a proposal in paragraph 6 that a form of quota penalties should be introduced for countries which fail to meet their fleet reduction targets annually.",
    "It says that this should be done despite the principle of relative stability.",
    "I believe that the principle of relative stability is a fundamental legal principle of the common fisheries policy and a proposal to subvert it would be legally inadmissible.",
    "I want to know whether one can raise an objection of that kind to what is merely a report, not a legislative proposal, and whether that is something I can competently do on Thursday.",
    "That is precisely the time when you may, if you wish, raise this question, i.e. on Thursday prior to the start of the presentation of the report.",
    "Madam President, coinciding with this year' s first part-session of the European Parliament, a date has been set, unfortunately for next Thursday, in Texas in America, for the execution of a young 34 year-old man who has been sentenced to death. We shall call him Mr Hicks.",
    "At the request of a French Member, Mr Zimeray, a petition has already been presented, which many people signed, including myself.However, I would ask you, in accordance with the line which is now constantly followed by the European Parliament and by the whole of the European Community, to make representations, using the weight of your prestigious office and the institution you represent, to the President and to the Governor of Texas, Mr Bush, who has the power to order a stay of execution and to reprieve the condemned person.",
    "This is all in accordance with the principles that we have always upheld.",
    "Thank you, Mr Segni, I shall do so gladly.",
    "Indeed, it is quite in keeping with the positions this House has always adopted.",
    "Madam President, I should like to draw your attention to a case in which this Parliament has consistently shown an interest.",
    "It is the case of Alexander Nikitin.",
    "All of us here are pleased that the courts have acquitted him and made it clear that in Russia, too, access to environmental information is a constitutional right.",
    "Now, however, he is to go before the courts once more because the public prosecutor is appealing.",
    "We know, and we have stated as much in very many resolutions indeed, including specifically during the last plenary part-session of last year, that this is not solely a legal case and that it is wrong for Alexander Nikitin to be accused of criminal activity and treason because of our involvement as the beneficiaries of his findings."

]